name: Destroy Infrastructure

on:
  workflow_dispatch:  # Only runs when manually triggered

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init with Backend
        run: |
          terraform -chdir=infra init \
            -backend-config="bucket=dami-tfstate-bucket" \
            -backend-config="key=ec2-infra/terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Terraform Destroy
        working-directory: infra
        run: terraform destroy -auto-approve -input=false

